CREATE TABLE login (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(150) NOT NULL
)ENGINE InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE permition (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	description VARCHAR(50) NOT NULL
)ENGINE InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE login_permition (
	id_login BIGINT NOT NULL,
	id_permition BIGINT NOT NULL,
	PRIMARY KEY (id_login, id_permition),
	FOREIGN KEY (id_login) REFERENCES login(id),
	FOREIGN KEY (id_permition) REFERENCES permition(id)
)ENGINE InnoDB DEFAULT CHARSET=UTF8MB4;

INSERT INTO login (email, password) VALUES ('jdr.richard@gmail.com', '$2a$10$fQfTcbzAyoCdOpCwyBJFhejPCE7z4TurFviOdOgKs16xUMz5b49GO');
