CREATE TABLE author (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	login VARCHAR(100) NOT NULL,
	name VARCHAR(255),
	avatar VARCHAR(255),
	biography TEXT
)ENGINE InnoDB DEFAULT CHARSET=UTF8MB4;

INSERT INTO author (login) VALUES ('RichardJd');